DROP TABLE 쿠폰이력 CASCADE;
DROP TABLE 포인트 CASCADE;
DROP TABLE 최근본상품 CASCADE;
DROP TABLE 주문상세 CASCADE;
DROP TABLE 장바구니 CASCADE;
DROP TABLE 상품문의 CASCADE;
DROP TABLE 리뷰 CASCADE;
DROP TABLE 재고 CASCADE;
DROP TABLE 배송 CASCADE;
DROP TABLE 결제 CASCADE;
DROP TABLE 이벤트 CASCADE;
DROP TABLE 개인문의 CASCADE;

DROP TABLE 주문 CASCADE;
DROP TABLE 상품 CASCADE;
DROP TABLE 쿠폰 CASCADE;

DROP TABLE 회원 CASCADE;
DROP TABLE 관리자 CASCADE;

commit;